version: "3.9"

services:
  frontend:
    image: aegisai-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    deploy:
      placement:
        constraints:
          - node.hostname == node1
