name: "OWASP ZAP DAST Scan"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  zap-dast:
    name: Run OWASP ZAP Baseline DAST Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create ZAP rules directory and rules file
      run: |
        mkdir -p .zap
        echo -e "90004\tIGNORE\tFalse positive on site isolation warning" > .zap/rules.tsv
        echo -e "90005\tIGNORE\tExpected missing header in dev" >> .zap/rules.tsv

    - name: Start Juice Shop Container
      run: |
        docker run -d -p 3000:3000 --name juice-shop bkimminich/juice-shop
        echo "Waiting for Juice Shop to become available..."
        for i in {1..30}; do
          if curl -s --head http://localhost:3000 | grep "200 OK" > /dev/null; then
            echo "Juice Shop is up!"
            break
          fi
          echo "Still waiting..."
          sleep 2
        done

    - name: Run ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://localhost:3000'
        fail_action: false
        rules_file_name: '.zap/rules.tsv'
        cmd_options: >
          -a -T 5 -j -r report_html.html -w zap_report.md
          -z "-config api.disablekey=true
              -config passiveScan.scanOnlyInScope=true
              -config scanner.level=High"

    - name: Upload ZAP HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report-html
        path: report_html.html

    - name: Upload ZAP Markdown Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report-md
        path: zap_report.md
